import Head from 'next/head';
import { useRouter } from 'next/router';
import useFetch from '../hooks/useFetch';
import PopSuccess from '../components/lib/pop-ups/popSuccess';
import { useState, useEffect } from 'react';
import { authStore } from '../global/auth.global';
import { EyeIcon, EyeOffIcon } from '@heroicons/react/outline';

export default function Home() {
  const router = useRouter();
  const [visible, setVisible] = useState(false);
  const { setSecret, secret_ID } = authStore();
  const [success, setsuccess] = useState(false);
  const { data, status, isLoading, refetch, error } = useFetch('ADMIN-LOGIN');

  // ======= onchange secret field -->
  const onSecretChange = (e) => {
    setSecret(e.target.value);
  };

  useEffect(() => {
    if (status === 'success') {
      setsuccess(true);
    }

    error && alert(error.message);
  }, [status]);

  return (
    <div className='w-full min-h-screen bg-gray-200 flex items-center justify-center'>
      <Head>
        <title>Admin Login</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='px-12 py-24 shadow-xl rounded bg-white flex flex-col gap-9 items-center'>
        <h1 className='text-3xl text-gray-700 font-primary font-bold text-center'>
          Claim System
        </h1>

        {/* ====== Secret ID field */}
        <div className='relative flex items-center justify-center flex-col'>
          {visible ? (
            <EyeOffIcon
              className='h-6 w-8 bottom-3 cursor-pointer absolute text-gray-600 right-3'
              onClick={() => setVisible((visible) => !visible)}
            />
          ) : (
            <EyeIcon
              className='h-6 w-8 bottom-3 cursor-pointer absolute text-gray-600 right-3'
              onClick={() => setVisible((visible) => !visible)}
            />
          )}
          <p className='font-secondary font-semibold text-gray-500 mb-3 self-start'>
            Enter your secret ID
          </p>
          <input
            className='px-9 py-3 h-12 w-96 border-none rounded-md focus:outline-clr-4 font-secondary bg-gray-200 shadow-sm'
            type={visible ? 'text' : 'password'}
            value={secret_ID}
            onChange={onSecretChange}
            placeholder='Secret ID'
          />
        </div>

        {/* ====== generate token key */}
        <button
          className='w-52 h-12 font-primary bg-clr-4 text-gray-200 shadow-md rounded text-lg'
          onClick={refetch}
        >
          Generate token
        </button>
        {isLoading && <p className='-mt-7'>loading...</p>}

        <PopSuccess
          title='Success'
          content='A onr time password (OTP) has been sent to your email!'
          state={success}
          setState={setsuccess}
          action={() => router.push('/dashboard')}
        />
      </main>
    </div>
  );
}
