import Head from 'next/head';
import { useState } from 'react';
import { useRouter } from 'next/router';
import { EyeIcon, EyeOffIcon } from '@heroicons/react/outline';

export default function Home() {
  const router = useRouter();
  const [secret, setSecret] = useState('');
  const [visible, setVisible] = useState(false);

  // ======= onchange secret field -->
  const onSecretChange = (e) => {
    setSecret(() => e.target.value.toUpperCase());
  };

  return (
    <div className='w-full min-h-screen bg-gray-200 flex items-center justify-center'>
      <Head>
        <title>Admin Login</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='px-12 py-24 shadow-xl rounded bg-white flex flex-col gap-9 items-center'>
        <h1 className='text-3xl font-primary font-bold text-center'>
          Claim System
        </h1>

        {/* ====== Secret ID field */}
        <div className='relative flex items-center justify-center'>
          {visible ? (
            <EyeOffIcon
              className='h-6 w-8 cursor-pointer absolute text-gray-600 right-3'
              onClick={() => setVisible((visible) => !visible)}
            />
          ) : (
            <EyeIcon
              className='h-6 w-8 cursor-pointer absolute text-gray-600 right-3'
              onClick={() => setVisible((visible) => !visible)}
            />
          )}
          <input
            className='px-9 py-3 h-12 w-96 border-none focus:outline-clr-4 font-secondary bg-gray-200 shadow-sm'
            type={visible ? 'text' : 'password'}
            value={secret}
            onChange={onSecretChange}
            placeholder='Secret ID'
          />
        </div>

        {/* ====== generate token key */}
        <button
          className='w-52 h-12 font-primary bg-clr-4 text-gray-200 shadow-md rounded text-lg'
          onClick={() => router.push('/dashboard')}
        >
          Generate token
        </button>
      </main>
    </div>
  );
}
